### PR TITLE
Adjust Differential to recent Timely changes

### LINKED ISSUE #642: Workflow "Test build against Timely master" failed
The workflow "**Test build against Timely master**" failed. See logs:
https://github.com/TimelyDataflow/differential-dataflow/actions/runs/17721617402

Commit: https://github.com/TimelyDataflow/differential-dataflow/commit/

// cc: @frankmcsherry, @antiguru — please triage and resolve this issue

### PR DESCRIPTION
**Pull request by antiguru**
Timely 0.24 compatibility.

Fixes #642

### CODE REVIEW

File: differential-dataflow/src/operators/reduce.rs [hunk 1]
```diff
@@ -533,7 +533,8 @@ where
                                 for (val, time, diff) in buffers[index].1.drain(..) {
                                     buffer.push_into(((T1::owned_key(key), val), time, diff));
                                     builders[index].push(&mut buffer);
-                                    buffer.clear();
+                                    // TODO: Clear!
+                                    // buffer.clear();
```
Comment (antiguru) [inline differential-dataflow/src/operators/reduce.rs:537]: This is a moment where we need to think a bit:
* We could add a constraint to `Input` that we can call `clear` in it. Easy, but also not forward-thinking.
* What we're doing here is building chunks from elements. We hope that the order of items in the chunk is the same as in `buffers`, otherwise we'd construct an invalid batch. Elsewhere, we'd use a container builder that feeds into a batcher, and the batcher's output is guaranteed to be suitable for the builder.
* We're also restricting the container to absorbing _owned_ data, but we might want references here.

Comment (antiguru) [reply differential-dataflow/src/operators/reduce.rs]: Changed to use `MergerChunk::clear` here. Not ideal, but works.

File: differential-dataflow/src/collection.rs [hunk 2]
```diff
@@ -155,6 +156,7 @@ impl<G: Scope, D, R, C: Container + Clone + 'static> Collection<G, D, R, C> {
     pub fn inspect_container<F>(&self, func: F) -> Self
     where
         F: FnMut(Result<(&G::Timestamp, &C), &[G::Timestamp]>)+'static,
+        C: IterContainer,
```
[the remark this answers is not in the document]
Comment (antiguru) [reply differential-dataflow/src/collection.rs]: Definitely not intended! Removed.
